### ISSUE TITLE
Download/Install new library

### ISSUE THREAD

**Issue by JojoG** [jackdreilly/SparkADMM#7]
Hey guys,

I am currently working on the LocalLogR and I want to use the ADMM method. To do so, I have the algorithm on § 8.2.2 . I need to use algorithms like L-BFGS to implement the x.
A routine exists in the "scalanlp" library. I would like to download it and then install it but I did not really follow when we did it for the "scalala" library...

Is it easy to do? Or should I wait for the next meeting? Because all what I need is here normally: "https://github.com/scalanlp/scalanlp-core"

Also I do not know if the L-BFGS routine from this library will work with the SparseDoubleMatrix1D we created... I don't think so actually...

Thank you for your help!

Johann

**Comment by jackdreilly** [comment]
Hey Johann,
This is a problem I have been working on recently.

We should definitely stick with the sparse matrix representation, because the matrices are just too inefficient otherwise. Therefore, we should abandon scalala in my opinion.

This means, we must write our own nonlinear unconstrained solver for the x-update step. There's an example of such a solution in the etc/ folder in matlab code provided by Boyd.

I've pushed some changes implementing a Newton's method solver for the x-update for a super-local version of the problem

**Comment by jackdreilly** [comment]
the problem is still open, since we may want to implement something other than the Newton's method, maybe using L-BFGS instead

**Comment by JojoG** [comment]
hello, 
No more working on it^^
I close it^^
Best,
Jojo

**Comment by jackdreilly** [comment]
that's a relief! Hey, I'm living in Paris now. Are you here? Bonne sante!

**Comment by JojoG** [comment]
Hey Jack,
Hehehe no no, I am leaving in Barcelona currently^^ But I'll be in Paris for 3 months this summer (I mean I hope)^^ Maybe we can have a drink or something^^ 
I still have the same gmail address. Don't hesitate to send me your phone number!
Stay safe ;)

**Comment by jackdreilly** [comment]
Sure thing! my number is +19167681755 looking forward to catching up at
some point!
